sources:
  # GraphQL Source for SpaceX
  - name: SpaceX
    handler:
      graphql:
        endpoint: https://api.spacex.land/graphql

  # GraphQL Source for infos on countries
  - name: Countries
    handler:
      graphql:
        endpoint: https://countries.trevorblades.com/

serve:
  exampleQuery: example-query.graphql
